CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(libgpiod C CXX)

SET(CMAKE_CXX_STANDARD 17)

FILE(GLOB gpiod_sources "${CMAKE_CURRENT_SOURCE_DIR}/lib/*.c")
ADD_LIBRARY(gpiod SHARED ${gpiod_sources})
TARGET_INCLUDE_DIRECTORIES(gpiod
    PUBLIC  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
            $<INSTALL_INTERFACE:include>
    PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/lib
            ${CMAKE_CURRENT_SOURCE_DIR}/lib/uapi
)
TARGET_COMPILE_DEFINITIONS(gpiod PRIVATE _GNU_SOURCE GPIOD_VERSION_STR="2.2.2")

FILE(GLOB gpiodcxx_sources "${CMAKE_CURRENT_SOURCE_DIR}/bindings/cxx/*.cpp")
ADD_LIBRARY(gpiodcxx SHARED ${gpiodcxx_sources})
TARGET_INCLUDE_DIRECTORIES(gpiodcxx
    PUBLIC  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/bindings/cxx>
            $<INSTALL_INTERFACE:include>
    PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/bindings/cxx
)
TARGET_LINK_LIBRARIES(gpiodcxx PUBLIC gpiod)
